#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER sysi5adm superuser;
  CREATE USER mainpower;
	CREATE DATABASE i5_TEST;
	GRANT ALL PRIVILEGES ON DATABASE 'i5_TEST' TO sysi5adm;
  CREATE DATABASE i5_TEST2;
	GRANT ALL PRIVILEGES ON DATABASE 'i5_TEST2' TO sysi5adm;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sysi5adm;
EOSQL