{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/employee_attendances": {
      "parameters": [
        {
          "name": "Content-Type",
          "in": "header",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "list employee_attendances",
        "tags": [
          "Employee Attendance"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "search_text",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page[page]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "page[limit]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "include",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[employee_id]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[date]",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/employee_attendances/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "id",
          "required": true,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "Content-Type",
          "in": "header",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "delete": {
        "summary": "delete employee_attendance",
        "tags": [
          "Employee Attendance"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/employee_attendances/mass_upload": {
      "post": {
        "summary": "mass upload employee attendance from absence machine report",
        "tags": [
          "Employee Attendance"
        ],
        "security": [
          {
            "bearer_auth": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "successful"
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "file"
              }
            }
          },
          "required": true
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{default_host}:{default_port}",
      "variables": {
        "default_host": {
          "default": "localhost"
        },
        "default_port": {
          "default": "3000"
        }
      }
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer_auth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}