refresh_discount:
  cron: "5 0 * * *"
  class: "RefreshAllPromotionJob"
  queue: default
toggle_customer_group_discount:
  cron: "5 0 * * *"
  class: "ToggleCustomerGroupDiscountJob"
  queue: default
backup_database:
  cron: "0 */1 * * *"
  class: "BackupDbJob"
  queue: low
refresh_report:
  cron: "20 */1 * * *"
  class: "RefreshReportJob"
  queue: low
remove_expired_image:
  cron: "5 0 * * *"
  class: "RemoveExpiredFileJob"
  queue: low
create_today_cashier_session:
  cron: "5 0 * * *"
  class: "CreateTodayCashierSessionJob"
  queue: default
