refresh_discount:
  cron: "20 6 * * *"
  class: "RefreshAllPromotionJob"
  queue: default
toggle_customer_group_discount:
  cron: "20 1 * * *"
  class: "ToggleCustomerGroupDiscountJob"
  queue: default
backup_database:
  cron: "0 */1 * * *"
  class: "BackupDbJob"
  queue: low
remove_expired_image:
  cron: "20 3 * * *"
  class: "RemoveExpiredFileJob"
  queue: low
create_today_cashier_session:
  cron: "10 6 * * *"
  class: "CreateTodayCashierSessionJob"
  queue: default
