refresh_discount:
  cron: "0 6 * * *"
  class: "RefreshAllPromotionJob"
  queue: low
toggle_customer_group_discount:
  cron: "20 1 * * *"
  class: "ToggleCustomerDiscountJob"
  queue: low
backup_database:
  cron: "0 */1 * * *"
  class: "BackupDbJob"
  queue: default
remove_expired_image:
  cron: "0 3 * * *"
  class: "RemoveExpiredFileJob"
  queue: default