refresh_discount:
  cron: "13 7 * * *"
  class: "RefreshAllPromotionJob"
  queue: default
toggle_customer_group_discount:
  cron: "12 7 * * *"
  class: "ToggleCustomerGroupDiscountJob"
  queue: default
backup_database:
  cron: "0 */1 * * *"
  class: "BackupDbJob"
  queue: low
remove_expired_image:
  cron: "11 7 * * *"
  class: "RemoveExpiredFileJob"
  queue: low
create_today_cashier_session:
  cron: "10 7 * * *"
  class: "CreateTodayCashierSessionJob"
  queue: default
