refresh_discount:
  cron: "6 16 * * *"
  class: "RefreshAllPromotionJob"
  queue: default
toggle_customer_group_discount:
  cron: "5 16 * * *"
  class: "ToggleCustomerGroupDiscountJob"
  queue: default
backup_database:
  cron: "0 */1 * * *"
  class: "BackupDbJob"
  queue: low
remove_expired_image:
  cron: "8 16 * * *"
  class: "RemoveExpiredFileJob"
  queue: low
create_today_cashier_session:
  cron: "9 16 * * *"
  class: "CreateTodayCashierSessionJob"
  queue: default
